project:
  type: book
  output-dir: docs

book:
  title: "Teal Insights' Guide to Working with the World Bank International Debt Statistics"
  author: "Teal Emery & The Teal Insights Team"
  date: "10/16/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - part: part1_foundations.qmd
      chapters: 
        - ids_overview.qmd 
        - ids_policy_relevant_qs.qmd
        - ids_data_creation.qmd
        - ids_strengths_limitations.qmd
    - part: part2_wbids.qmd
      chapters: 
        - wbids_getting_started.qmd
        - wbids_common_workflows.qmd
        - wbids_integrating_data.qmd
    - part: part3_wrapping_up.qmd
      chapters: 
        - summary.qmd
        - references.qmd

bibliography: references.bib

format:
  html:
    theme: cerulean
    code-fold: true
    code-summary: "Show the code"
    code-tools: true
  pdf:
    documentclass: scrreprt

editor: visual

