project:
  type: book
  output-dir: docs

book:
  title: "Teal Insights' Guide to Working with the World Bank International Debt Statistics"
  author: "Teal Emery & The Teal Insights Team"
  date: "10/16/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - part: part1-foundations.qmd
      chapters: 
        - ids-overview.qmd 
        - ids-policy-relevant-qs.qmd
        - ids-data-creation.qmd
        - ids-strengths-limitations.qmd
    - part: part2-wbids.qmd
      chapters: 
        - wbids-getting-started.qmd
        - wbids-common-workflows.qmd
        - wbids-integrating-data.qmd
    - part: part3-wrapping-up.qmd
      chapters: 
        - summary.qmd
        - references.qmd

bibliography: references.bib

format:
  html:
    theme: cerulean
    code-fold: true
    code-summary: "Show the code"
    code-tools: true
  pdf:
    documentclass: scrreprt

editor: visual

